"""Remove exchange_rates table - use real-time API instead

Revision ID: 5ca7fe6e37db
Revises: d671e51094c8
Create Date: 2025-10-28 17:30:56.567577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca7fe6e37db'
down_revision: Union[str, Sequence[str], None] = 'd671e51094c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchange_rates_date'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('source', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('base', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('rate', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_rates_pkey')),
    sa.UniqueConstraint('base', 'symbol', 'date', name=op.f('uix_base_symbol_date'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Daily exchange rates from external API'
    )
    op.create_index(op.f('ix_exchange_rates_date'), 'exchange_rates', ['date'], unique=False)
    # ### end Alembic commands ###
